fix: set minimal supported Node.js version to 14
mswjs/msw pull request #1160
Opened 2022-03-10 16:58 UTC by kettanaito

Follow up to https://github.com/mswjs/msw/pull/1136

2022-03-10 17:08 UTC, MichaelDeBoey requested changes

2022-03-10 17:08 UTC, MichaelDeBoey commented on .github/workflows/ci.yml
> +        node: [14.19.0, 16.14.0]
You can just use the latest version instead of running on specific Node version
```suggestion
        node: [14, 16]
```

2022-03-10 17:10 UTC, kettanaito commented on .github/workflows/ci.yml
> +        node: [14.19.0, 16.14.0]
Good catch. I was wondering if it'd support it this way 👍

2022-03-10 17:11 UTC, kettanaito commented
We need to update `interceptors` and perhaps other ecosystem packages to also allow Node.js 14.

2022-03-11 14:10 UTC, MichaelDeBoey approved these changes

2022-03-11 14:12 UTC, merged

2022-03-12 07:03 UTC, baptisteArno commented
Does this fix `msw@0.39.1: The engine "node" is incompatible with this module. Expected version ">=16.x". Got "14.18.1"`?

2022-03-12 11:17 UTC, kettanaito commented
@baptisteArno, precisely.

2022-03-15 14:04 UTC, kettanaito commented
:tada: This PR is included in version 0.39.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/msw/v/0.39.2)
- [GitHub release](https://github.com/mswjs/msw/releases/tag/v0.39.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-15 15:21 UTC, thedavidprice commented
Thank you @kettanaito Count me in if ever there's a way I can reciprocate collaboration!

2022-05-17 23:48 UTC, kettanaito commented
## Released: v0.40.0 🎉

This has been released in v0.40.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.40.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.40.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.