feat(createsetupserver.ts): add listHandlers method that returns acti…
mswjs/msw pull request #1369
Opened 2022-08-24 17:35 UTC by AlexeiDarmin

**Change overview**

This PR adds a `listHandlers()` method that returns a list of currently active handlers as suggested in https://github.com/mswjs/msw/issues/474#issuecomment-1225571039.

> You can list currently active handlers via [server.printHandlers()](https://mswjs.io/docs/api/setup-server/print-handlers). Alas, it prints the handlers summary stdout instead of returning a list. If you are interested, it'd be awesome to have a change where printHandlers() returns a list of handlers:

**Additional change proposal**

Now that devs would have access to individual handlers, handlers would benefit from having a `.toString()` or `.stringSummary()` to easily see a string summary of the handler. The logging logic within `printHandlers` could be moved to `handler.toString()`, then `printHandlers` would simply be:

```typescript
 printHandlers() {
        currentHandlers.forEach((handler) => {
          console.log(handler.toString())
        })
      }
```

2022-08-25 11:06 UTC, kettanaito commented
Hey, @AlexeiDarmin. Thank you for opening this on such a short notice!

I absolutely agree with the summary proposal and `.toString()` on individual handlers. A great idea. Would you have a chance to add it to this pull request?

2022-08-25 11:10 UTC, kettanaito commented on src/node/createSetupServer.ts
> +        return currentHandlers
We need to be cautious exposing internals, and `currentHandlers` is internals. I fear that developers will be tempted to meddle with this array directly. That should never happen. They should use explicit APIs like `use` or `resetHandlers` to affect the list of handlers, and `listHandlers()` must be purely readonly. 

Maybe let's make this array readonly before exposing it?

```ts
// First, guard the array on the type level.
listHandlers(): ReadonlyArray<RequestHandler> {
  // Second, prevent mutations on runtime.
  const immutableHandlers = [...currentHandlers]
  Object.freeze(immutableHandlers)
  return immutableHandlers
}
```

2022-08-25 11:10 UTC, kettanaito commented on src/node/glossary.ts
> +  listHandlers(): RequestHandler<RequestHandlerDefaultInfo, MockedRequest<DefaultBodyType>, any, MockedRequest<DefaultBodyType>>[]
If we go to the readonly list route (which I think we should), let's adjust this return type as well.

2022-08-25 11:11 UTC, kettanaito requested changes
I absolutely love the changes! The only suggestion I have is to make sure that we expose a readonly array from `listHandlers()` so that people are not tempted to mutate it.

2022-08-25 11:12 UTC, kettanaito commented
Since we're not deprecating `printHandlers()` just yet, I will rename this change to be a `fix`.

2022-08-30 11:14 UTC, kettanaito commented
I've covered some of the previous suggestions, also added `listHandlers` to the worker API. Let's see if the tests pass.

2022-08-30 11:16 UTC, kettanaito approved these changes

2022-08-30 12:09 UTC, merged

2022-08-30 14:00 UTC, AlexeiDarmin commented
@kettanaito thanks for applying the changes! I appreciate your feedback and was going to incorporate when I had a minute.

2022-08-31 00:32 UTC, kettanaito commented
## Released: v0.46.0 🎉

This has been released in v0.46.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.46.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.46.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.