feat(packages): bump interceptors@0.17.6
mswjs/msw pull request #1441
Opened 2022-10-20 07:48 UTC by Taillook

Update interceptors version, because audit report is critical.

```
# npm audit report

@xmldom/xmldom  <0.7.6
Severity: critical
```

2022-10-20 09:31 UTC, kettanaito requested changes
Hey, @Taillook. Thanks for opening this.

I don't think this change is necessary. MSW depends on a range version for the interceptors package (`^`). If you re-install `msw` you will get the latest patch version of the interceptors, and the xmldom vulnerability will be fixed. 

```
npm install msw -D
npm ls @mswjs/interceptors
```

Let me know if I'm missing something here.

2022-10-20 09:44 UTC, Taillook commented
Oh, I misskate. Thanks for tearching me.

2022-10-20 10:18 UTC, kettanaito commented
Let me know if you get the fixed version following the steps I've shared. It should work that way but let's double-check.

2022-10-20 11:04 UTC, closed without merging

2022-10-21 08:45 UTC, Taillook commented
Problems resolved. Thanks.