fix(typescript): support typescript 5.0
mswjs/msw pull request #1566
Opened 2023-03-17 02:41 UTC by mattcosta7

broaden typescript support to include 5.0

2023-03-17 02:45 UTC, mattcosta7 commented on .github/workflows/ci.yml
> +        ts: ['4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5.0']
do we have a set number of versions to support? should we pop off the `4.4`?

2023-03-17 15:33 UTC, kettanaito commented on .github/workflows/ci.yml
> +        ts: ['4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5.0']
@mattcosta7, yes, I'd drop 4.4 in this change.

2023-03-17 15:35 UTC, kettanaito requested changes
Thanks for adding TS 5 support, @mattcosta7!

Could you please add a typings test for ts 5 in [here](https://github.com/mswjs/msw/tree/main/test/typings) as well? This way we will have a bit more assurance that the library compiles and runs correctly with that ts version. Thanks.

2023-03-17 16:15 UTC, mattcosta7 commented
> Thanks for adding TS 5 support, @mattcosta7!
> 
> Could you please add a typings test for ts 5 in [here](https://github.com/mswjs/msw/tree/main/test/typings) as well? This way we will have a bit more assurance that the library compiles and runs correctly with that ts version. Thanks.

sure thing - probably won't have time until later today or tomorrow though!

2023-03-17 19:55 UTC, mattcosta7 commented
think that should do it https://github.com/mswjs/msw/pull/1566/commits/84f3ac878608f95f0a418adfe93baa443285d3f9

2023-03-20 09:51 UTC, kettanaito approved these changes
Thanks, @mattcosta7! Let's ship this.

2023-03-20 09:51 UTC, merged

2023-03-20 10:10 UTC, oteoe commented
when can we expect a release ?

2023-03-20 13:07 UTC, kettanaito commented
## Released: v1.1.1 🎉

This has been released in v1.1.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v1.1.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/1.1.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.