Create CHANGELOG.md
mswjs/msw pull request #391
Opened 2020-09-21 09:46 UTC by balavishnuvj

2020-09-21 16:27 UTC, msutkowski commented
Hey @balavishnuvj, the `CHANGELOG` you're looking for can be found here: https://github.com/mswjs/msw/releases. An example of a `CHANGELOG.md` file that would better suit this repo can be seen here if you'd like to mimic it and update this PR: https://github.com/reduxjs/redux/blob/master/CHANGELOG.md.

Thanks!

2020-09-22 04:19 UTC, balavishnuvj commented
@msutkowski it was very similar, I had adapted from https://github.com/testing-library/react-testing-library/blob/master/CHANGELOG.md

Have updated though :)

2020-09-22 07:22 UTC, marcosvega91 commented
@balavishnuvj unfortunately MSW is not configured to work with  [semantic-release](https://github.com/semantic-release/semantic-release). `semantic-release` is a tool to auto release versions based on commits. For now this process is manually.

2020-09-22 08:08 UTC, kettanaito requested changes
One nitpick and it's good to go!

2020-09-22 08:08 UTC, kettanaito commented on CHANGELOG.md
> +# CHANGELOG
Nitpick: Let's write this in a regular case: `# Change Log`.

2020-09-22 17:43 UTC, kettanaito approved these changes

2020-09-22 17:43 UTC, merged