fix: check setupWorker and setupServers args
mswjs/msw pull request #402
Opened 2020-09-27 14:14 UTC by marcosvega91

2020-10-01 05:24 UTC, kettanaito requested changes

2020-10-01 05:24 UTC, kettanaito commented on test/msw-api/setup-worker/setupWorker.mocks.ts
> +// @ts-ignore
Can you please add a comment that this is an intentionally invalid usage?

2020-10-01 05:24 UTC, kettanaito commented on test/msw-api/setup-worker/setupWorker.test.ts
> +import * as path from 'path'
Lets rename this test suite so it’s clear what it does: `input-validation.test.ts`.

2020-10-01 05:24 UTC, kettanaito commented on src/node/createSetupServer.ts
> +          `[MSW] setupServer function receive every handler as an arg. You should call it as setupServer(...requestHandlers) with requestHandlers the array of handlers.`,
- please don’t use contractions (args)
- we should include the wrong usage example, presumably how the user tried to call this function.
- we shouldn’t assume the user knows about the `requestHandlers` list (the name is rather internal)

```
[MSW] Failed to call “setupServer”: received a list of request handlers (setupServer([a, b])), expected to receive each handler individually: setupServer(a, b).

2020-10-01 10:30 UTC, marcosvega91 commented
I have updated the repo, sorry for this stupid mistakes 😅

2020-10-06 07:40 UTC, kettanaito approved these changes
Thank you for adding this, @marcosvega91! I've retouched the `setupServer` test a little and change the terminology slightly in the error message. Let's wait for the CI.

2020-10-06 07:53 UTC, marcosvega91 commented
thank you @kettanaito 😃

2020-10-06 07:56 UTC, merged