Fix duplicate parameter in function with default parameter values
mswjs/msw pull request #470
Opened 2020-11-22 01:24 UTC by psoch

**Summary**

When running an msw service worker with storybook in Safari I get the following error: `SyntaxError: Duplicate parameter 'onUnhandledRequest' not allowed in function with default parameter values.` It seems to be related to usage of the same function and parameter name in this [file](https://github.com/mswjs/msw/blob/e1656555e925d672b576e974716ad8e5e0a8aa18/src/utils/request/onUnhandledRequest.ts). 

(For reference I found a similar type of issue in safari in another library https://github.com/jupyterlab/jupyterlab/pull/7993)

2020-11-22 09:26 UTC, kettanaito commented on src/utils/request/onUnhandledRequest.ts
> +  onUnhandledReq: OnUnhandledRequest = 'bypass',
Let's name this parameter `handler`.

That way we don't have to shorten it while still preserving its semantic meaning: a function that handles an `onUnhandled` event.

2020-11-22 09:27 UTC, kettanaito requested changes
Hi, @psoch. Thank you for creating a pull request with this improvement!

I've left one comment, could you please take a look?

2020-11-23 16:01 UTC, kettanaito approved these changes
This is awesome! Thank you, @psoch, and welcome to contributors!

2020-11-23 16:01 UTC, merged

2020-11-23 16:05 UTC, psoch commented
Thank you @kettanaito for the feedback, quick response, and great library!